### ISSUE TITLE
Rename python package from kfmd to kubeflow.metadata

### ISSUE THREAD

**Issue by jlewi** [kubeflow/metadata#106]
/kind feature

**Describe the solution you'd like**

Currently the SDK is imported as

```
import kfmd
```

Should we change this to be

```
kubeflow.metadata
```

So that we have a single top level Kubeflow package with multiple sub packages?

/cc @jian-he @animeshsingh 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by zhenghuiwang** [comment]
Yes, I support have a single package `kubeflow` so that users need only pip install one package instead of many packages.

Where should the `kubeflow` package source code be put? I guess a subpackage can still be developed in its own repo and be exported via`kubeflow.<subpackage>`.

**Comment by jinchihe** [comment]
/assign

I'm working for kubeflow.fairing now.
