### ISSUE TITLE
Installation of metadata service

### ISSUE THREAD

**Issue by zhenghuiwang** [kubeflow/metadata#11]
As the first step of https://github.com/kubeflow/metadata/issues/9. We need A kustomize  component to install metadata service in KF cluster.

Make sure the metadata service is reachable. (We can ping the health endpoint of metadata service if KF is installed from Master). 

/cc @neuromage @jlewi @mvartakAtVerta @terrytangyuan @ywskycn

**Comment by jlewi** [comment]
Should we split this up into sub issues?

**Comment by zhenghuiwang** [comment]
This is a separate issue on the actual implementation #8. This one is about the service (a hello world implementation https://github.com/kubeflow/metadata/pull/3) can be installed from KF Master.

**Comment by jlewi** [comment]
@zhenghuiwang How's this coming? Are we on track to complete this by end of week?

**Comment by zhenghuiwang** [comment]
I didn't get a chance to work on it last week. But i will start it today or tomorrow. Should be able to finish it on time.

**Comment by jlewi** [comment]
@zhenghuiwang Any update on this?

**Comment by zhenghuiwang** [comment]
PRs are under reivew. The issue can be closed once the PRs are merged.
