### ISSUE TITLE
How to make original ArtifactType 

### ISSUE THREAD

**Issue by TomomasaTakatori** [kubeflow/metadata#120]
In python SDK, kinds of ArtifactType are only Dataset, Model, and Metrics.
If another ArtifactTypes is needed, we can't make them (We could can do by using module generated by open_api, but there is no document ).
And kfmd's concepts is slightly differed from original MLMD library. For example, ExecutionType is not able to be define.

Summarization
- Easily making original ArtifactType (If currently can, please tell me how to do it ) .
- Following MLMD library.

**Comment by dreamryx** [comment]
Assume **ws1** is your workspace create by "metadata.Workspace". You can create an ArtifactType named **tomoma_type** with tree fileds as below:

```
artifactType = openapi_client.MlMetadataArtifactType(
    name="kubeflow.org/alpha/tomoma_type",
    properties={
        "owner":"STRING",
        "create_time":"STRING",
        "description":"STRING",
    })  
response = ws1.client.create_artifact_type(artifactType)
```

I agree that the SDK should be more convenient to use.  I want to update the sdk later.

**Comment by TomomasaTakatori** [comment]
Thank you for your replying.

I understand If we would like to create ArtifactType, we should write original code.

And the type of ExecutionType is just "kubeflow.org/alpha/execution". 
Is it the same as ArtifactType to create ExecutionType, that mean we need to write original code ?

**Comment by dreamryx** [comment]
Yes. If you want to create new executionType, you need to write the similar code showed above. The sdk python lib is only for the pre-defined type and objects. :)

**Comment by TomomasaTakatori** [comment]
Thank you so much.
