### ISSUE TITLE
What's 'Run' meaning in kfmd ?

### ISSUE THREAD

**Issue by TomomasaTakatori** [kubeflow/metadata#121]
In kfmd python SDK, Run class is implemented, but I can't understand what it is because MLMD library can't have this concept.

My Thought:
Run class object seems to be describe how execution works. 
Yet, ExecutionType just implemented Execution class whose ExecutionType is "kubeflow.org/alpha/execution". So Run object in the Execution class could be used to distinguish one Execution from others. 
But if original ExecutionType is created, we don't need to distinguish between Executions to use Run object. In this case, we can decide whether Run object use. 

My Questions:
- In kfmd, ExecutionType keep one Type in the future, and Execution is distinguish by using 'Run' ?
- If we would like to make original ExecutionType,  how to deal with 'Run' in this case ?

**Comment by dreamryx** [comment]
The info of run and workspace is just custom property of the execution. The execution is distinguished by its name and id. If you want make original execution type, you need to submit a createExecutionType request to the server. The thing in sdk is for pre-defined artifact and execution which could used in pipeline.

**Comment by TomomasaTakatori** [comment]
I've understood, thank you.
