### ISSUE TITLE
Add documentations for Python SDK

### ISSUE THREAD

**Issue by gabrielwen** [kubeflow/metadata#134]
SDK is easy to use but would be great if we have documentation as reference.

**Comment by zhenghuiwang** [comment]
Thanks for raising the issue! All SDK related docs are listed in [this section](https://www.kubeflow.org/docs/components/misc/metadata/#using-the-metadata-sdk-to-record-metadata) on Kubeflow Website. Which part do you think should be expanded?

I expect the SDK usage to be straightforward to readers who go through [this demo notebook](https://github.com/kubeflow/metadata/blob/master/sdk/python/sample/demo.ipynb).

**Comment by zhenghuiwang** [comment]
The Metadata SDK ref docs are now available:
https://kubeflow-metadata.readthedocs.io/en/latest/


This issue duplicates
https://github.com/kubeflow/website/issues/1206
