### ISSUE TITLE
Create Metadata spec for model, metrics, workspace and etc

### ISSUE THREAD

**Issue by zhenghuiwang** [kubeflow/metadata#17]
part of #4 

Create the basic type spec for model, metrics, execution, workspace etc so that we can save/retrieve these data directly.

It is not intended to be comprehensive for all use cases.

/assign @zhenghuiwang

**Comment by animeshsingh** [comment]
@zhenghuiwang we would like to collaborate on this one. Any place where you meet, have meeting etc. to discuss this further?

**Comment by zhenghuiwang** [comment]
@animeshsingh I'm working on a PR for it. We can discuss it in the PR.
