### ISSUE TITLE
Make metadata db optional

### ISSUE THREAD

**Issue by xaniasd** [kubeflow/metadata#171]
/kind feature

**Describe the solution you'd like**
In the current setup, metadata deploys a database in the base layer. This database is insecurely configured (e.g. root password "test"). Production deployments will (hopefully) want to use a different setup; especially for cloud deployments, managed SQL services such as RDS in AWS are good replacement candidates. 

It is possible to customize the metadata deployment with an overlay and avoid using metadata-db, I would like to avoid deploying it altogether. 

**Anything else you would like to add:**
We can solve this by moving metadata-db related resources out of the base layer. I'm more than happy to submit a PR if the solution is acceptable.

**Comment by discordianfish** [comment]
Fully agree, we'd strongly prefer using RDS for this as well.

@jlewi Any reason to believe a PR for this might be controversial? I assume it would mean making the deployment optional and expose config parameters to specify an external database? Or do we need a design doc here?

@xaniasd Let me know if I can help

**Comment by jlewi** [comment]
@zhenghuiwang heads up the metadata efforts so he would be the person to talk to.

**Comment by zhenghuiwang** [comment]
@xaniasd @discordianfish Sounds good. Free feel to make a PR in Manifests. Thanks!

**Comment by xaniasd** [comment]
@discordianfish thanks for bumping this (I had almost forgotten about it). In my view it's a straightforward change so I can take a first stab at it. I'll link it here so that you can review it as well.

@zhenghuiwang will do asap
