### ISSUE TITLE
Add endpoints to Create and Read metadata

### ISSUE THREAD

**Issue by zhenghuiwang** [kubeflow/metadata#19]
part of #5 

Add endpoints to CRUD metadata for predefined types.

/assigne @zhenghuiwang

**Comment by jlewi** [comment]
@zhenghuiwang Any update on this?

**Comment by jlewi** [comment]
@neuromage Could you provide an update please on this issue? What is the remaining work to be done?

**Comment by jlewi** [comment]
@neuromage ping?

**Comment by neuromage** [comment]
Fixed with #49
