### ISSUE TITLE
[MLMD Lineage] Always show scroll bars or an indication of scrolling

### ISSUE THREAD

**Issue by kwasi** [kubeflow/metadata#195]
/kind feature
/area metadata
/area front-end

* Can be achieved with a transparent mask

**Comment by avdaredevil** [comment]
- The option we discussed in the meeting if we didn't want to mess with the scrollbars was to show a `#fff` to `transparent` fade in the part of the screen that had a scrollbar. Obviously it becomes slightly less of a problem once #193 is tackled.
- Another option is to use CSS ([example here](https://stackoverflow.com/questions/7492062/css-overflow-scroll-always-show-vertical-scroll-bar)) that would enforce a scrolling style that would be platform independent. 
  - Caveat: It will only work for `webkit` browsers: Chrome, Edge
- Use JS to create scrollbars (platform-independent, unique style, slower, browser agnostic)
