### ISSUE TITLE
Can not pip the metadata sdk

### ISSUE THREAD

**Issue by b675987273** [kubeflow/metadata#203]
/kind bug

**What steps did you take and what happened:**
```shell
richard@richard-VirtualBox:~$ pip install kubeflow.metadata
/home/richard/.local/lib/python2.7/site-packages/pip/_vendor/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
  warnings.warn(warning, RequestsDependencyWarning)
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting kubeflow.metadata
  ERROR: Could not find a version that satisfies the requirement kubeflow.metadata (from versions: none)
ERROR: No matching distribution found for kubeflow.metadata
WARNING: You are using pip version 19.2.2, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Metadata version:
- Kubeflow version:
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by b675987273** [comment]
But that command works at the jupyter. Interesting!!

**Comment by zhenghuiwang** [comment]
The metadata SDK works only for python 3.5+

Your command line is running `pip install` under python 2.7. That's why it can't find any suitable version.

The notebook server uses python3 by default.

You should be able to run `python3 -m pip install` in your terminal.
