### ISSUE TITLE
[MLMD] Sync up changes from Pipelines to Execution / Artifacts view

### ISSUE THREAD

**Issue by avdaredevil** [kubeflow/metadata#217]
## About
With MLMD changes complete, and all lineage components in [kubeflow/frontend](https://github.com/kubeflow/frontend). There are some other components that would make sense to migrate:
- [x] ArtifactDetails.tsx
- [x] ExecutionDetails.tsx
- [x] ExecutionList.tsx

@Bobgy Would there be a way to make sure all future changes are propagated similarly, for the time being. I understand that creating shared versions of these components makes sense in the longer term, but I do not have the cycles to carry forward that change currently.

### Current Plan
Manually review the diffs and update the files in this repo, so all the new Lineage Relevant updates are present here as well

### Meta
/area metadata
/area front-end
/priority p1
/assign @avdaredevil
/cc @kwasi

**Comment by Bobgy** [comment]
@avdaredevil Thanks for filing the issue!

I think there's no easier way other than creating shared components.
I can see if I can put these into KFP 1.0 plan if you don't have cycles, but I don't expect any changes in those components for the foreseeable future. Maybe it's not very urgent.

One question what does `all the new Lineage Relevant updates` mean?

**Comment by Bobgy** [comment]
Actually, I guess the next major features for those pages is: https://github.com/kubeflow/pipelines/issues/3157 and adding server side pagination.
