### ISSUE TITLE
Bazel build

### ISSUE THREAD

**Issue by animeshsingh** [kubeflow/metadata#22]
Do we really need bazel build? Seems its not much adopted outside Google, hence if we can avoid?

**Comment by zhenghuiwang** [comment]
I think we can eventually avoid bazel. We only need it to update proto file and generated code now.

We will keep the repository working with Go tools.

**Comment by jinchihe** [comment]
Yes, I suggest using the Go tool such as `dep` which is used by other project under kubelow such as KFServing. I do not why still say no dependency after `bazel` steps.

**Comment by zhenghuiwang** [comment]
The reason we have bazel is that MLMD library that we depends on is in C++ and bazel is easy to use to manage cross language build.

Right now, the codebase works well with `go mod` and other go tools. You only need to `bazel build` first, which generates  go dependency files. After that, all Go tools work.

Go module is the future direction and we should avoid `dep`.

**Comment by jinchihe** [comment]
Oh... I misunderstand. Thank you got pointing out this.
