### ISSUE TITLE
metadata-writer pod does not start: Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by nicbillen** [kubeflow/metadata#253]
/kind bug

**What steps did you take and what happened:**
I have installed Kubernetes 1.17.16 together with Istio 1.3.1 on a new BareMetal cluster. Afterwards I have used https://raw.githubusercontent.com/kubeflow/manifests/v1.1-branch/kfdef/kfctl_istio_dex.v1.1.0.yaml to install Kubeflow (without the two istio dependencies istio-stack and istio). The whole system starts. But the metadata-writer pod stucks.

The console output shows:

"Illegal instruction (core dumped)" (nothing more)

**What did you expect to happen:**

A runnable metadata-writer pod ;-)

**Environment:**

- Metadata version: gcr.io/ml-pipeline/metadata-writer:1.0.0
- Kubeflow version: kfdef/kfctl_istio_dex.v1.1.0.yaml
- Kubernetes version: 

Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:09:25Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.16", GitCommit:"d88fadbd65c5e8bde22630d251766a634c7613b0", GitTreeState:"clean", BuildDate:"2020-12-18T12:07:12Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

- OS (e.g. from `/etc/os-release`):

NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

All the best
Nicolas Billen

**Comment by qinjie545** [comment]
I‘v got the same problem, waiting for resolving.

Best regards!

**Comment by mageru** [comment]
Getting this behavior on OpenShift 4.6.13 as well with OpenDataHub 1.0.0 using gcr.io/ml-pipeline/metadata-writer:1.0.4
