### ISSUE TITLE
Handle exception when Type is not found

### ISSUE THREAD

**Issue by souvik-deepsource** [kubeflow/metadata#254]
When creating an object from the `Execution` class, the `_type_id` variable stores the id of the execution type by querying the Type table in the database. During first executions, it is natural that the type won't be present and thus the database will throw an error. This error is blocking when running the [demo notebook](https://github.com/kubeflow/metadata/blob/master/sdk/python/sample/demo.ipynb). The error thrown is as shown below.

```
ERROR:absl:mlmd client NotFoundError: No type found for query: kubeflow.org/alpha/execution
```

https://github.com/kubeflow/metadata/blob/86ca46dbe82f91c0a049645e9573b170600be2d7/sdk/python/kubeflow/metadata/metadata.py#L284

**Comment by harshit-deepsource** [comment]
Use Kubeflow v1.1.0 and it should work just fine.
