### ISSUE TITLE
Broken link in README

### ISSUE THREAD

**Issue by ZxMYS** [kubeflow/metadata#261]
/kind bug

The README says 'For more information, you can visit [this page](https://www.kubeflow.org/docs/components/metadata/).', but the page redirects to kubeflow document index page and it doesn't show a metadata component.

**Comment by ZxMYS** [comment]
It is there in 1.2 doc https://v1-2-branch.kubeflow.org/ tho

**Comment by theadactyl** [comment]
Thank you! Updated here: https://github.com/kubeflow/metadata/pull/265
