### ISSUE TITLE
Set up e2e test for presubmit test

### ISSUE THREAD

**Issue by zhenghuiwang** [kubeflow/metadata#28]
Metadata service currently calls MLMD to manage MySql database. While we have unit tests using MLMD's in memory storage, it is ideal to have e2e tests. 

We can start set up the e2e tests framework:
1. Start  metatadata service in kubeflow-ci cluster.
2. Start mysql server.
3. Make sure metadata server can send request to mysql server. (e.g. `/resource` endpoint) Later we may want to send a sequence of requests to various endpoints and check the responses.

All above need to write Argo workflows triggered by ksonnet. See instructions [here](https://github.com/kubeflow/testing#writing-an-argo-workflow-for-an-e2e-test).

**Comment by zhenghuiwang** [comment]
@terrytangyuan Would you be interested in working on it? Thanks

**Comment by terrytangyuan** [comment]
@zhenghuiwang Thanks! I am still catching up with my projects after KubeCon so I don't think I will be available to work on this at the moment. However, I'll update this issue when I start working on it.

**Comment by zhenghuiwang** [comment]
Thanks @terrytangyuan !

I have cycles this week and will finish it before v0.6 release.

/assign @zhenghuiwang
