### ISSUE TITLE
Define metadata service API

### ISSUE THREAD

**Issue by zhenghuiwang** [kubeflow/metadata#5]
For [v0.6 CUJ](http://bit.ly/kf-meta-cuj), we need to define metadata service API:
1. It should provide endpoints to create, read, update and delete metadata.
2. It should be able to connect related metadata in a machine learning workflow.
3. A UI for the CUJ can be built on top of this API and the built-in metadata(#4), 
4. It can handle customized metadata in a similar way to built-in metadata.

**Comment by jlewi** [comment]
@zhenghuiwang How's this coming?

**Comment by zhenghuiwang** [comment]
@neuromage and I should be able to send out a proposal this week.

**Comment by zhenghuiwang** [comment]
#24

**Comment by jlewi** [comment]
@zhenghuiwang What is the remaining work to be done on this issue?

**Comment by zhenghuiwang** [comment]
An update on 4 items in this issue:

> 1. It should provide endpoints to create, read, update and delete metadata.

It is almost done. We have CRUD endpoints for artifact, artifact type, execution and execution types.
Some API changes for artifact proto definition need to do.

> 2. It should be able to connect related metadata in a machine learning workflow.

This is a stretch goal for logging the input/output relation between artifact and its execution. We may finish it later for artifact tracking with SDK and UI after this release.

> 3. The CUJ can be built on top of this API and the built-in metadata(#4),

It is done. Built-in metadata definitions for this CUJ are merged and can be loaded during service start.

> 4.It can handle customized metadata in a similar way to built-in metadata.

It is done. Built-in metadata are registered by the artifact type and execution type endpoints.

**Comment by zhenghuiwang** [comment]
lineage tracking API is also added to the backend.
