### ISSUE TITLE
Swagger client generation from service specification doesn't generate all methods

### ISSUE THREAD

**Issue by prodonjs** [kubeflow/metadata#55]
/kind bug

**What steps did you take and what happened:**
Ran the following command to generate a Typescript client library from the Metadata service specification using version [2.4.5](https://github.com/swagger-api/swagger-codegen/releases/tag/v2.4.5)
`java -jar swagger-codegen-cli.jar generate -i ../api/service.swagger.json -l typescript-fetch -o ./src/apis/service -c ./swagger-config.json`

**What did you expect to happen:**
Client library with generated methods for each of the following operations to be defined:
```
CreateArtifact,
CreateArtifactType,
CreateExecution,
CreateExecutionType,
DeleteArtifact,
DeleteArtifactType,
DeleteExecution,
DeleteExecutionType,
GetArtifact,
GetArtifactType,
GetExecution,
GetExecutionType,
ListArtifacts,
ListArtifacts2,
ListArtifactTypes,
ListExecutions,
ListExecutions2,
ListExecutionTypes
```

The actual methods created were as follows:
```
createArtifact
createArtifactType
createExecution
createExecutionType
deleteExecutionType
getExecutionType
listArtifactTypes
listArtifacts
listArtifacts2
listExecutionTypes
listExecutions
listExecutions2
```
The following methods were not generated:
```
DeleteArtifact,
DeleteArtifactType,
DeleteExecution,
GetArtifact,
GetArtifactType,
GetExecution
```

**Anything else you would like to add:**
Running `java -jar swagger-codegen-cli.jar validate -i ../api/api.swagger.json` shows no errors. However, pasting the definition into https://editor.swagger.io/ shows the following error message, which seems to indicate an issue with multiple paths of the form `/api/v1alpha1/{name}`
![Screenshot from 2019-06-17 10-29-51](https://user-images.githubusercontent.com/6835846/59612318-df9f0b00-90ea-11e9-8cd5-f129541fa7f3.png)

**Environment:**
Using `api/service.swagger.json` from master.
**swagger-code-cli** [2.4.5](https://github.com/swagger-api/swagger-codegen/releases/tag/v2.4.5)

**Comment by wing328** [comment]
Was gonna suggest you to try [openapi-generator](https://github.com/OpenAPITools/openapi-generator) (a fork of swagger codegen) instead but seems like the openapi spec/document may not be valid as I got the following errors using [Swagger/OpenAPI Valldator](https://apidevtools.org/swagger-parser/online/):
```
wagger-cli validate https://raw.githubusercontent.com/kubeflow/metadata/master/api/service.swagger.json
Swagger schema validation failed.
  Additional properties not allowed: collectionFormat at #/definitions/ml_metadataUnionArtifactStructType/properties/candidates

JSON_OBJECT_VALIDATION_FAILED
```

(disclosure: I'm the top contributor to both OpenAPI Generator and Swagger Codegen)

**Comment by zhenghuiwang** [comment]
Thank you @wing328 for the suggestion! I discovered and used openapi-generator for python because of some other issues of swagger-codegen.

@prodonjs I have used openapi-generator to generate swagger python client in the Makefile
https://github.com/kubeflow/metadata/blob/master/Makefile#L31

I tried to genereate a client for typescript, which seems not to have the issues you mentioned above. Would you mind verifying if this works for you?

```
swagger-js-client:
	mkdir -p /tmp/swagger/js_client
	./api/generate_proto.sh && \
	wget http://central.maven.org/maven2/org/openapitools/openapi-generator-cli/4.0.1/openapi-generator-cli-4.0.1.jar -O /tmp/swagger/swagger-codegen-cli.jar && \
    java -jar /tmp/swagger/swagger-codegen-cli.jar generate \
    	-i api/service.swagger.json \
    	-g typescript-node \
    	-o /tmp/swagger/js_client && \
	rm -rf js_client && \
    cp -r /tmp/swagger/js_client js_client
```

**Comment by prodonjs** [comment]
So I was not performing was running the `generate_proto.sh` script first, but I assumed that the existing JSON files checked into the repo were the result of previously running this.

When I run the latter half of the command on the existing files, I get the same result for both the Typescript and Python libraries. Only the *get* and *delete* methods included in the generated code are for execution types.

**Comment by zhenghuiwang** [comment]
You're right. There are some methods missing from the generated code. We use `name`/`parent` to represent multiple path segments for various endpoints, resulting overlapped paths. (This is recommended annotation path pattern by Google Could though..)

Your fix would solve the problem for now. If you're blocked by this, we can merge your PR.

But a problem is that `swagger.json` is also generated. Your manual change would be overwritten by the script if we later changes `service.proto`. 

https://github.com/kubeflow/metadata/blob/master/api/generate_proto.sh#L59

has more context on the problem of generating swagger file.

I can change the `sed` command to generate different param names, but I don't know how to auto correct the corresponding `parameter { "name": "XXX"..` fields. We probably have to manually correct these fields before we have some python/Go code to do it.

**Comment by prodonjs** [comment]
I see I wasn't even thinking about the fact that the regeneration of the spec files would remove any changes. I don't think this will be blocking because I can make the change manually and then generate the client libraries and check them in with our changes for the front-end. However, we would need to make the same manual changes again when the service API is updated. For now, I think I can proceed and we can determine a way to address the generated specification later.
