### ISSUE TITLE
Create a Python library for v0.6

### ISSUE THREAD

**Issue by zhenghuiwang** [kubeflow/metadata#6]
Create a Python library for logging metadata in Notebook and Kubeflow Pipeline:

- Create `workspace` to organize machine learning projects.
- Create a `run` of notebook and pipeline.
- CRUD `artifact`(data_set, model, metrics, HPs)  and `execution` information in a run.
- Link the relations among workspace, run, artifacts, and executions.

**Comment by johnugeorge** [comment]
It would be easier if we can list down apis that would be supported in this release

**Comment by zhenghuiwang** [comment]
Updated the description of Python API.

**Comment by jlewi** [comment]
@zhenghuiwang Any update on this? It looks like some PRs have been merged. What is the remaining work?

**Comment by zhenghuiwang** [comment]
**What is done**

> 1. Create workspace to organize machine learning projects.
> 2. Create a run of notebook and pipeline.
> 3. CRUD artifact(data_set, model, metrics, HPs)

We can log artifacts information, group them by run and workspace, and list existing artifacts. With all these, we can have a basic experience for our v0.6 notebook CUJ.

**What is not done and probably won't be in v0.6 release**
> log `execution` information.
> Link the relations among workspace, run, artifacts, and executions.

Given the time we have, it makes more sense to deliver all these together for execution tracking and 
artifact lineage tracking along with UI.

**Comment by jlewi** [comment]
Need to get lineage functionality working and then this is done.

**Comment by PsHughes** [comment]
![Last Word Logo](https://user-images.githubusercontent.com/50753712/60124167-a865d500-974e-11e9-98b3-538669bb53fb.jpg)
If I did this correctly.  The logo is L over W.  Preview shows sideways. @PsHughes.

**Comment by jlewi** [comment]
@zhenghuiwang Any update on this?

**Comment by zhenghuiwang** [comment]
#69 is under review and will complete the Python SDK for v0.6.
