### ISSUE TITLE
Add basic lineage logging for model, data, and metrics in notebook

### ISSUE THREAD

**Issue by zhenghuiwang** [kubeflow/metadata#60]
/kind feature

**Describe the solution you'd like**
Improve the current backend/PyClient to have a lineage tracking for notebook. For the demo book we should have information which dataset generates the model and the metrics.

**Comment by ryandawsonuk** [comment]
Could I ask where I can find the demo book?

**Comment by zhenghuiwang** [comment]
@ryandawsonuk The [demo notebook source code](https://github.com/zhenghuiwang/metadata/blob/cec82de6a1d6f33d9258929195f80698910a0857/sdk/python/demo.ipynb) is linked in PR #69 

Once the SDK being published, the notebook should be able to run in KF notebook service.
