### ISSUE TITLE
Create a UI for v0.6

### ISSUE THREAD

**Issue by zhenghuiwang** [kubeflow/metadata#7]
This UI can show models and workflows in Notebook and Kubeflow Pipeline.

**Comment by jlewi** [comment]
@avdaredevil @zhenghuiwang Any update on this?

**Comment by zhenghuiwang** [comment]
We have finished the review of UI mocks including artifact list view and model details view.

What will be delivered in v0.6 is the list view of artifacts, including dataset, metrics and models.

**Comment by jlewi** [comment]
@rileyjbauer Are you planning on working on this?

**Comment by prodonjs** [comment]
@jlewi Yes @rileyjbauer , Jing and myself will be working on the Metadata UI and plan to get started in earnest this week with the goal of having the artifacts list view in place for 0.6 and a stretch goal to have the model details view.

**Comment by yupbank** [comment]
is there a link for the UI mockups ?

**Comment by prodonjs** [comment]
I don't know that we have any yet that are publicly shared.

**Comment by jlewi** [comment]
@prodonjs How's this coming? Will we have something this week?

**Comment by prodonjs** [comment]
Yep we've got good progress being made with a basic list and details view. We should have this baseline functionality checked in today or tomorrow and available for testing within a deployment.

**Comment by zhenghuiwang** [comment]
Thanks @prodonjs and @rileyjbauer!

We have a UI with listing and detail view of artifacts for v0.6.
