### ISSUE TITLE
Metadata sevice Implementation for v0.6

### ISSUE THREAD

**Issue by zhenghuiwang** [kubeflow/metadata#8]
Implement the API defined in #5 for v0.6.

**Comment by jlewi** [comment]
@zhenghuiwang Any update on this? It looks like a bunch of PRs have been opened.

What is the remaining work to be done?

**Comment by zhenghuiwang** [comment]
What is done:
CRUD for artifacts and artifact types.
CRUD for execution and execution types.

The only remaining change is some protobuf definition change of artifact.

**Comment by jlewi** [comment]
Is this blocked by #19 ? How can the service be ready if we don't have read and create endpoints which is what #19 is providing?

**Comment by jlewi** [comment]
Need to create some endpoints for lineage.

**Comment by zhenghuiwang** [comment]
#65 and #66 will add lineage tracking support in the backend.
